# version: "3.7"
# services:
#   # rabbitmq:
#   #   image: rabbitmq:3-management
#   #   environment:
#   #     RABBITMQ_DEFAULT_VHOST: "/players"
#   #     RABBITMQ_DEFAULT_USER: "dev"
#   #     RABBITMQ_DEFAULT_PASS: "dev"
#   #   volumes:
#   #     - type: volume
#   #       source: rabbitmq
#   #       target: /var/lib/rabbitmq/mnesia
#   #   ports:
#   #     - "5672:5672"
#   #     - "15672:15672"
#   #   networks:
#   #     - local
#   redis:
#     image: redis:5.0.5
#     volumes:
#       - type: volume
#         source: redis
#         target: /data
#     ports:
#       - "6379:6379"
#     command: redis-server --appendonly yes
#     # networks:
#     #   - local
#   mongodb:
#     image: mongo:4.2
#     ports:
#       - "27017:27017"
#     # environment:
#     #   MONGO_INITDB_DATABASE: "admin"
#     #   MONGO_INITDB_ROOT_USERNAME: "root"
#     #   MONGO_INITDB_ROOT_PASSWORD: "root"
#     volumes:
#       # - type: bind
#       #   source: ./mongodb/docker-entrypoint-initdb.d
#       #   target: /docker-entrypoint-initdb.d
#       - type: volume
#         source: mongodb
#         target: /data
#     # networks:
#     #   - local
#   api:
#     build: ./api
#     image: zonions:latest
#     ports:
#       - 1337:1337
#       - 9337:9337
#     environment:
#       PORT: 1337
#       DEBUG_PORT: 9337
#       # WAIT_HOSTS: rabbitmq:5672,mongodb:27017,redis:6379
#       WAIT_HOSTS: mongodb:27017,redis:6379
#       NODE_ENV: development
#       MONGODB_URL: mongodb://localhost:27017/zonionz?authSource=admin
#     volumes:
#       - type: bind
#         source: ./api
#         target: /usr/src/app/api
#       - type: bind
#         source: ./api/config
#         target: /usr/src/app/config
#     # networks:
#     #   - local
#     depends_on:
#       # - "rabbitmq"
#       - "mongodb"
#       - "redis"
#   web:
#     build: ./assets
#     image: zonions:latest
#     ports:
#       - 8080:8080
#     environment:
#       # REACT_APP_API_URL: http://api.players.local
#       REACT_APP_API_URL: http:localhost:8080/

#     volumes:
#       - type: bind
#         source: ./assets/src
#         target: /usr/src/app/src
#       - type: bind
#         source: ./assets/public
#         target: /usr/src/app/public
#     # networks:
#     #   - local
#     depends_on:
#       - "api"
#   # nginx:
#   #   build: nginx
#   #   image: nginx-wait:latest
#   #   restart: on-failure
#   #   environment:
#   #     WAIT_HOSTS: api:1337,web:3000
#   #   volumes:
#   #     - type: bind
#   #       source: ./nginx/conf.d
#   #       target: /etc/nginx/conf.d
#   #     - type: bind
#   #       source: ./nginx/log
#   #       target: /var/log/nginx
#   #   ports:
#   #     - 80:80
#   #   networks:
#   #     - local
#   #   depends_on:
#   #     - "api"
#   #     - "web"
# # networks:
# #   local:
# #     driver: overlay

# volumes:
#   rabbitmq:
#   redis:
#   mongodb:

version: "3"
services:
  service1:
    container_name: zonions-container
    image: zonions-image:V0.0.1
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
      - "1337:1337"
      - "9229"
    links:
      - mongo_api
  mongo_api:
    container_name: mongodb
    image: mongo:4.2
    volumes:
      - dataVolume:/data/db
    ports:
      - "27019:27017"
  redis_api:
    container_name: redis
    image: redis
    ports: 
      - "6380:6379"
volumes:
   dataVolume:
