
version: "3"
services:
  service1:
    container_name: zonions-container
    image: zonions-image:V0.0.1
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
      - "1337:1337"
      - "9229"
    links:
      - mongo_api
  mongo_api:
    container_name: mongodb
    image: mongo:4.2
    volumes:
      - dataVolume:/data/db
    ports:
      - "27019:27017"
  redis_api:
    container_name: redis
    image: redis
    ports: 
      - "6380:6379"
volumes:
   dataVolume:
